### PR TITLE
removing named import

### LINKED ISSUE #116: `5.2.0` introduces a breaking change
The [`5.2.0` release](https://github.com/alexreardon/memoize-one/releases/tag/v5.2.0) accidentally introduced a breaking change when using CommonJS `require()`.

`5.1.1`:

```
> require('memoize-one')
[Function: memoizeOne]
```

`5.2.0`:

```js
> require('memoize-one')
{ default: [Function: memoizeOne], memoizeOne: [Function: memoizeOne] }
```

### PR DESCRIPTION
**Pull request by alexreardon**
Fixes #116. Will undo the problematic addition of named imports.

Plan

- merge this change
- release 5.2.1
- deprecate 5.2.0

### CODE REVIEW

**Review by TrySound — APPROVED** [review]

**Comment by alexreardon** [comment]
Still need to update flow types

**Comment by alexreardon** [comment]
https://github.com/alexreardon/memoize-one/issues/116#issuecomment-826242002

**Comment by alexreardon** [comment]
@Offirmo just confirming you broke because you moved over to the new named import?

**Comment by Offirmo** [comment]
@alexreardon no, it broke suddenly, hence my visit on your page. I'm using memoize-one in node.js. It used to work like this:

```
const memoize_one = require('memoize-one')

const find_next_element = memoize_one(...expensive computation
                          ^
TypeError: memoize_one is not a function
```

With your change in 5.2.0 it no longer worked. I guess I would have had to turn it to `const memoize_one = require('memoize-one').default`

**Comment by Offirmo** [comment]
@alexreardon so no, don't bother keeping 5.2.0, it's a broken release, just deprecate it.

**Pull request merged**
