### PR TITLE
Now handling exceptions. Closes #31

### LINKED ISSUE #31: error messages not thrown on memoized calls
memoizeOne seems not to throw errors when the function call is memoized. 

For example, in the function below I would expect the second call to `throwingDivide` to throw an error, but it does not. Is this behavior expected? 

```js
var memoizeOne = require("memoize-one")

function _throwingDivide(x, y) {
  if (y===0) {
    throw Error('cannot divide by zero')
  }
  return x/y
}

const throwingDivide = memoizeOne(_throwingDivide)

try {
  throwingDivide(4, 0)
}
catch (error) {
  console.log(error)
}

console.log(throwingDivide(4, 0)) // does not throw !
```

Thanks for this library—love it's simplicity!

### PR DESCRIPTION
**Pull request by alexreardon**
Inspired by #32

### CODE REVIEW

**Comment by alexreardon** [comment]
Thanks @scinos for your help with this one

**Comment by alexreardon** [comment]
- [x] code
- [x] tests
- [x] docs

**Comment by jamiebuilds** [comment]
This seems like a bad default behavior, caching errors is almost always a mistake.

For example, this would break code that is used in retry-able code paths:

```js
const memoizeOne = require('memoize-one');
const pRetry = require('p-retry');

pRetry(memoizeOne(mayThrowErrorsOnOccasion), { retries: 5 }).then(result => {
  // ...
});
```

**Comment by alexreardon** [comment]
You are right @jamiebuilds. I have created a follow up PR #35

**Pull request merged**
